name = "coup-shadow-protocol"
main = "worker.ts"
compatibility_date = "2024-02-20"

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
PROTOCOL_PASSWORD = "Qwerasdf"
Model_Alpha = "gemini-3-flash-preview"
Model_Beta = "deepseek-reasoner"
